name: QuickSell
version: ${project.version}
authors: [mrCookieSlime, PhilTheSkid]
website: http://thebusybiscuit.github.io/
depend: [Vault]
softdepend: [mcMMO, Citizens, PrisonGems]

main: me.mrCookieSlime.QuickSell.QuickSell

api-version: 1.16

commands:
  sell:
    description: Allows you to quickly sell your Items
    usage: /sell
  booster:
    description: Starts a Booster
    usage: /booster <Player> <Multiplier> <Duration in Minutes>
  pbooster:
    description: Starts a private Booster
    usage: /pbooster <Player> <Multiplier> <Duration in Minutes>
  quicksell:
    description: Allows you to manage your Shops
    usage: /quicksell
  boosters:
    description: Shows you all active Boosters
    usage: /boosters
  sellall:
    description: Allows you to quickly sell all your Items to a specific Shop
    usage: /sellall <Shop>
  prices:
    description: Allows you to see what Items can be sold in your Shop
    usage: /prices <Shop>

permissions:
  quicksell.sign.create:
    description: Allows you to create SELL Signs
    default: op
  quicksell.booster:
    description: Allows you to create a Booster
    default: op
  quicksell.admin:
    description: Allows you to manage Shops
    default: op
  quicksell.help:
    description: Help Menu
    default: op
  quicksell.editor:
    description: Allows you to use the in-game editor
    default: op
  quicksell.stopboosters:
    description: Allows you to stop boosters
    default: op
  quicksell.linknpc:
    description: Allows you to Link NPCs
    default: op
  quicksell.unlinknpc:
    description: Allows you to Un-Link NPCs
    default: op
  quicksell.prices.anyshop:
    description: Allows you to see the prices for any shop
    default: op
  quicksell.prices:
    description: Allows you to do /prices
    default: op
  quicksell.sell:
    description: Allows you to run /sell
    default: op
  quicksell.sellall:
    description: Allows you to run /sellall
    default: op